[project]
name = "gradio-demo"
version = "0.1.0"
description = "Gradio demo application"
authors = [
    { name = "coffee", email = "253864830@qq.com" },
]
dependencies = []

[project.optional-dependencies]
emscripten = ["urllib3~=2.0"]

[tool.setuptools]
python-requires = ">=3.8, <3.13"

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple/"